spring.application.name=Hospital_Management_project


spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db
spring.datasource.username=root
spring.datasource.password=TIGER

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Set log level
logging.level.root=INFO

# Save logs to file
logging.file.name=logs/app.log

# Customize log format (optional but good)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger - %msg%n


spring.jpa.open-in-view=false